<<<<<<< HEAD
# Generated by Django 3.2.13 on 2022-04-26 14:15
=======
# Generated by Django 3.2.13 on 2022-04-27 18:05
>>>>>>> cf850b81cb804a98e531ba51de6dfffe13209ce9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0003_alter_meta_datafim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='nome',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nome'),
        ),
    ]
